### PR TITLE
Added Navidrome

### PR DESCRIPTION
**Pull request by lilkidsuave**
Tested on my repo
probably needs url change.

[here is a screenshot](https://imgur.com/ZPHswLX)

### CODE REVIEW

**Comment by lilkidsuave** [comment]
nevermind on url change

**Comment by azukaar** [comment]
Thanks and good job,
could you make the /data a volume please? like for other containers on the markets, the main config point is always a volume
otherwise it's perfect thanks!

**Comment by lilkidsuave** [comment]
/data is now a volume
your welcome

**Comment by azukaar** [comment]
Sorry I accidentally merged the PR but there are a lot of issues with it, so I ended up removing the folder. Please re-open the PR again :)

- dataPath is not required anymore
- Don't use navidrome as the container name but the service name
- Use a local icon
- :ro is not required on the music path
- The format you are using for the env var map is wrong, you need to use env=var in a list
- "if": "Context.adminOnly" and "if": "Context.dataPath" do not exist as functions

(I am guessing you ChatGPT it? Nothing wrong with it but yeah it does have quite a few issues)

**Comment by lilkidsuave** [comment]
> Sorry I accidentally merged the PR but there are a lot of issues with it, so I ended up removing the folder. Please re-open the PR again :) (make sure you rebase the branch or you're gonna have a conflict)
> 
> * dataPath is not required anymore
> * Don't use navidrome as the container name but the service name
> * Use a local icon
> * :ro is not required on the music path
> * The format you are using for the env var map is wrong, you need to use env=var in a list
> * "if": "Context.adminOnly" and "if": "Context.dataPath" do not exist as functions
> 
> (I am guessing you ChatGPT it? Nothing wrong with it but yeah it does have quite a few issues)

1. Ok I'll remove it
2. Ok
3. Ok
4. It's in the recommended Navidrome Compose on the Website
https://www.navidrome.org/docs/installation/docker/
5. Ok
6. This is based on the Jellyfin Compose in this very repository 
https://github.com/azukaar/cosmos-servapps-official/blob/master/servapps/Jellyfin/cosmos-compose.json
7.  I did have some help for formatting and finding errors.
8. Sorry

**Comment by azukaar** [comment]
NP, about the 6. If you refer to the "IF" thing in jellyfin, if you compare your file with the JF one
- Yours has if: "condition" in objects
- The JF one has {if condition} {/if}

**Pull request merged**
