### PR TITLE
Remove DockerMailServer screenshot

### PR DESCRIPTION
**Pull request by jwr1**
docker-mailserver does not come with any UI by default, it is solely operated by the CLI. The screenshot included is of a completely different project (https://github.com/jeboehm/mailserver-admin) and should be removed so as to not cause confusion.

### CODE REVIEW

**Comment by azukaar** [comment]
This is a good point, but I like having screenshots, may be the compose file should add an option to start mailserver-admin alongside the mailserver instead of just cutting the screenshots?

**Comment by jwr1** [comment]
From what I understand, https://github.com/docker-mailserver/docker-mailserver is completely separate from https://github.com/jeboehm/mailserver-admin. https://github.com/jeboehm/mailserver-admin is the admin interface for https://github.com/jeboehm/docker-mailserver, not https://github.com/docker-mailserver/docker-mailserver, so there's no way we can add it to the compose file.

Even though there's not an admin UI we can add, we could add an option to set up Roundcube, which is a webmail app; this could be what's shown in a screenshot.

**Comment by jwr1** [comment]
I'll close this for now, and I (or someone else) can set up Roundcube in a different pull request.

**Comment by azukaar** [comment]
> From what I understand, https://github.com/docker-mailserver/docker-mailserver is completely separate from https://github.com/jeboehm/mailserver-admin. https://github.com/jeboehm/mailserver-admin is the admin interface for https://github.com/jeboehm/docker-mailserver, not https://github.com/docker-mailserver/docker-mailserver, so there's no way we can add it to the compose file.

Ah I see! I misunderstood it then. But yes the conclusion is, ideally we would add a UI to it, and fix the screenshot accordingly

**Pull request closed without merging**
