### PR TITLE
Fasten Health App Added

### PR DESCRIPTION
**Pull request by jeffgallini**
Early stage app which allows you request records from medical providers and store on your hardware.

I think I did this right. Let me know if the docker compose needs work. I have a couple of other apps that I think would be great.

### CODE REVIEW

**Comment by lilkidsuave** [comment]
No need for the ports section anymore as you are routing using "routes: "

**Comment by lilkidsuave** [comment]
Target for data should go to /opt/fasten/db according to this
https://github.com/fastenhealth/fasten-onprem/blob/main/docker-compose.yml
Could also add another volume (type=bind) for a config.yml (also in link above)

**Comment by lilkidsuave** [comment]
Source for data probably should be named "{ServiceName}-data"

**Comment by azukaar** [comment]
/docker-compose.yml Could also add another volume (type=bind) for a config.yml (also in link above)

Should be a volume to the folder, otherwise it's going to trip on a bind on a single file

**Comment by jeffgallini** [comment]
Thanks everyone, I'll fix it and add it later today

**Comment by jeffgallini** [comment]
Since you have the 9090 host port and the 8080 container port, do I need multiple routes for each of them?
```
"ports":
     "9090:8080"
```

**Comment by lilkidsuave** [comment]
No. That one line is just mapping 9090 to 8080. Once you have the route setup for the container port(8080), you don't need that line. On this app, no ports section necessary.

**Comment by lilkidsuave** [comment]
You could model after other apps that ask for a directory for configs and replace the target/config with {Context.configpath}

**Comment by lilkidsuave** [comment]
This is going to sound picky(because it is) but double check spacing is correct in volumes(and in general), JSON is picky about spacing.

**Comment by jeffgallini** [comment]
@azukaar FYI, I just tested it out. The latest version is running when installed via the cosmos-installer. I'm leaving the paths as default for now, if needed, I can try changing them. But it's there if someone wants to make the change.

**Comment by azukaar** [comment]
Thanks!

**Pull request merged**
