### PR TITLE
Add CollaboraOnline servapp

### PR DESCRIPTION
**Pull request by jwr1**
I have most of what's needed for Collabora here, but I'm having a problem with opening Nextcloud documents. I will update here when I figure out what's wrong.

### CODE REVIEW

**Comment by azukaar** [comment]
I"m guessing you need a link between this and nextcloud right?
You can check in the *arr compose where it asks you for a link to a downloader for inspiration

**Comment by jwr1** [comment]
From what I understand, both Nextcloud and Collabora need to have publicly accessible URLs (https://collabora.example.com), instead of using internal links (http://Collabora:9800).

**Comment by azukaar** [comment]
I will check tomorrow on my end

**Comment by azukaar** [comment]
OK so here's what I found out: Essentially Nextcloud is trying to embed collabora in a weird way, which Cosmos won't let it do because it is unsecure (it jsut embeds a website with a cross-origin URL).

To make it work, either we need to disable the security (which is not an option at the moment, and probably shouldn't be) or we make it so that collabora is under the same subdomains as Nextcloud. I kinda got it to work I think, but Nextcloud being the mess that it is, refused to update the URL to the new one and kept trying to use the old one (Why? NO IDEA).

but I was able to disaply the document in Collabora by going to the URL manually basically.

Here's what you can replace the URL with in your cosmos-compose file : 

```

        {
          "name": "Nextcloud-{ServiceName}",
          "description": "Your Nextcloud instance hostname (to use with {ServiceName})",
          "useHost": true,
          "target": "https://{ServiceName}:9980",
          "UsePathPrefix": true,
          "PathPrefix": "/collabora",
          "AcceptInsecureHTTPSTarget": true,
          "mode": "SERVAPP",
          "Timeout": 14400000,
          "ThrottlePerMinute": 12000,
          "BlockCommonBots": true,
          "SmartShield": {
            "Enabled": true
          },
          "hideFromDashboard": true
        }
```

Then you should be able to use https://nextcloud.domain.com/collabora as your server URL

I will try again later but I think I need to resetup my Nextcloud again because it is currently in oblivion (just the usual Nextcloud stuff)

**Comment by azukaar** [comment]
OK so it does not work with a /path because Nextcloud is too dumb and instead of appending the document to it, it replaces the whole path making it impossible this way.
I have tried something else that seems to work: using collabora.nextcloud.domain.com (two levels subdomain). Since nextcloud.domain.com is considered an ancestor of this domain, the browser wont block it. The only caveat is, wildcard certificate wont cover it, but that's ok because Nextcloud has an option for the collabora HTTPS cert to be insecure.
I can now have a 200 response when Nextcloud opens the document.

Unfortunately the document still does not open though.. May be some ip whitelisting issues I'm not sure..

**Comment by jwr1** [comment]
I just tried it by putting the Collabora paths directly under Nextcloud's domain (like cloud.example.com/browser, cloud.example.com/cool, etc.), which seems to work better. [Collabora's reverse proxy](https://sdk.collaboraonline.com/docs/installation/Proxy_settings.html) guide has a list of all the paths needed. Now I'm just having trouble with getting the web sockets working correctly. With nginx, you're supposed to use the following:
```nginx
 location ~ ^/cool/(.*)/ws$ {
   proxy_pass https://127.0.0.1:9980;
   proxy_set_header Upgrade $http_upgrade;
   proxy_set_header Connection "Upgrade";
   proxy_set_header Host $http_host;
   proxy_read_timeout 36000s;
 }
```
I'm not sure how to set that up correctly with Cosmos though.

**Comment by jwr1** [comment]
Also, I tried using regexes in the path prefix field (like `/hosting/(capabilities|discovery)`) but they didn't seem to work. Are regexes not supported yet?

**Comment by jwr1** [comment]
Maybe it would be best to merge this with the Nextcloud config (have an option that enables Collabora). I'm assuming that's what most people are using it for anyway, and at the moment, all of the Collabora routes needed to be manually reordered to be under the Nextcloud routes. Overall, it would probably streamline the experience better.

**Comment by azukaar** [comment]
1 - Websocket are always on for all routes
2 - Regex work but they have a different syntax, see the Lemmy API route for an example, and https://github.com/gorilla/mux doc
3 - I agree that this would be even better as a Nextcloud option rather than standalone

thanks for the good work!

**Comment by jwr1** [comment]
Everything else should work now, I'm still having trouble with the web socket problem though. In Firefox, I'm getting this error:
```
Firefox can’t establish a connection to the server at wss://cloud.example.com/cool/https%3A%2F%2Fcloud.example.com%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F13_oclxncfql9l3%3Faccess_token%3D1Lk3xNVTQ0ORX23MWOvH4NTVZxLwTHdZ%26access_token_ttl%3D1690348279000/ws?WOPISrc=https%3A%2F%2Fcloud.example.com%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F13_oclxncfql9l3&compat=/ws.
```
Chromium gives me this (a little more helpful):
```
WebSocket connection to 'wss://cloud.example.com/cool/https%3A%2F%2Fcloud.example.com%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F13_oclxncfql9l3%3Faccess_token%3DO3FpsyQPmTtBHv1CScbhmFUrgfJ1lCCy%26access_token_ttl%3D1690348564000/ws?WOPISrc=https%3A%2F%2Fcloud.example.com%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F13_oclxncfql9l3&compat=/ws' failed: Error during WebSocket handshake: Unexpected response code: 301
```

**Comment by azukaar** [comment]
301 is a redirection, check the location header to see where the server is trying to redirect your socket

**Comment by jwr1** [comment]
There are 0 response headers for those requests, so no `location`.

**Comment by jwr1** [comment]
Closing this for now, as I'm not sure how to fix the problem. If someone else wants to add Collabora, they can use this as a starting point for the needed configuration. For my own use, I just decided to use Nexcloud AIO, and it works almost perfectly.

**Pull request closed without merging**
