### PR TITLE
Adding Dozzle

### PR DESCRIPTION
**Pull request by di5cord20**
Here’s a PR to add Dozzle to the market.

I bind mounted the docker.sock.  Not sure if that is the best way so feel free to update for something more secure.

P.S. this is my first foray into git and my very first PR!  I was inspired to contribute by @azukaar and the fantastic job he’s doing on the project and supporting people through Discord.  A thanks also goes out to @EvanTrow for helping me figure out how to configure git to complete a PR.

### CODE REVIEW

**Comment by azukaar** [comment]
This is a great PR, well done :D 
Merging, thank you!

**Comment by di5cord20** [comment]
I think I understand.  Should a new docker socket proxy container be created (new market app?) and then connect Dozzle to that container instead of mapping the docker.sock bind mount?  I found an example here (https://github.com/htpcBeginner/docker-traefik/blob/4a2bf6c0c266e55caf0bc3580b10893aa00d45d9/docker-compose-t2.yml#L200 and https://www.smarthomebeginner.com/traefik-docker-security-best-practices/#9_Use_a_Docker_Socket_Proxy)

if so, the same approach could be used by other apps that may need docker.sock (I.e., uptime-kuma when monitoring the container).

**Comment by azukaar** [comment]
You can setup the proxy as a container inside the same cosmos-compose like you would do with a docker-compose and multiple container. It would help ensure the app is secured by default

**Comment by rani-linea** [comment]
Does that mean you'd need to do the same in other apps as well or would it be accessible to other apps automatically?

**Comment by di5cord20** [comment]
Does that mean you’d need to do same for any other app you want to connect to the socket proxy (I.e., uptime-kuma) or would they have access to the one created inside Dozzle?

**Comment by azukaar** [comment]
Yes they would require the same attention

**Comment by di5cord20** [comment]
I have updated both the Dozzle and Uptime-Kuma apps and will push the PR.  I tested locally but encourage others to do so as well.  The new version will ask if you want to use a socket-proxy.  It will then ask if you already have one.  If yes, you need to select the container.  If no, it will create one for you.

**Pull request merged**
