### PR TITLE
Update Ryot configuration

### LINKED ISSUE #153: Update Ryot configuration
From https://github.com/azukaar/Cosmos-Server/issues/296

### What happened?

Hi! I'm the maintainer of Ryot. I'm getting a lot of support requests on Discord because the ryot configuration seems to be outdated. 

I'd be very grateful if the instructions could be updated. https://docs.ryot.io

I think the icon is outdated too.

Thanks!

### What should have happened?

Cosmos Ryot not working.

### How to reproduce the bug?

N/A

### Relevant log output

_No response_

### Other details

_No response_

### System details

N/A

### PR DESCRIPTION
**Pull request by IgnisDa**
Fixes #153.

### CODE REVIEW

**Comment by IgnisDa** [comment]
@azukaar There also needs to be a `TZ` env variable set to for example `Asia/Kolkata`. All other compose files say `TZ=auto`. Should I use that too and cosmos will automatically set the correct value?

**Comment by IgnisDa** [comment]
Does cosmos has the concept of generated variables? There is an env variable `ADMIN_ACCESS_TOKEN` which should ideally be a secure 32 characters long.

**Comment by IgnisDa** [comment]
THe 32 characters is not a hard requirement. Can you check if the configuration is fine?

**Comment by azukaar** [comment]
You're missing one bit, something like this: https://github.com/azukaar/cosmos-servapps-official/blob/master/servapps/Nextcloud/cosmos-compose.json#L30

This allows Cosmos to force persisting env var when reinstalling apps from the market (because you keep the volumes so the tokens need to persist otherwise you lose access to the data on the volume). I am thinking you probably need to persist the admin token? Correct me if Im wrong 

Other than that it looks good

**Comment by IgnisDa** [comment]
Thanks. I fixed it.

On a different note, shouldn't that property be a string array instead?

**Comment by azukaar** [comment]
> On a different note, shouldn't that property be a string array instead?

It's a docker label, it can only be a string

**Pull request merged**
