### PR TITLE
Handbrake - fixed description name

### PR DESCRIPTION
**Pull request by di5cord20**
Sorry, forgot to update the description name on this one as well.

### CODE REVIEW

**Comment by azukaar** [comment]
Why did you remove the tags? It still need some otherwise it might break the UI  I think

**Comment by di5cord20** [comment]
Honestly, I never know what to put in those tags or how people used them.  The previous tags were the Duplicati tags as I copied that folder when creating Handbrake.  I can add them back but honestly not sure how they are used or what to include.

**Comment by azukaar** [comment]
Something like ["media", "video", "conversion"] may be?

**Comment by di5cord20** [comment]
> Something like ["media", "video", "conversion"] may be?

Done.  Will do the same now for MKVToolNix

**Comment by azukaar** [comment]
Looks good but you should open a new PR because otherwise there is a conflict (or you can solve the conflict) thanks :)

**Comment by di5cord20** [comment]
> Looks good but you should open a new PR because otherwise there is a conflict (or you can solve the conflict) thanks :)

I'll submit a new PR.  Feel free to delete this one.  Thanks

**Pull request closed without merging**
